# Generated by Django 5.0.6 on 2024-06-07 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achat',
            fields=[
                ('achat_id', models.AutoField(primary_key=True, serialize=False)),
                ('achat_iban', models.CharField(max_length=34)),
                ('achat_date_prelevement', models.DateTimeField()),
                ('achat_montant', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Vol',
            fields=[
                ('vol_id', models.AutoField(primary_key=True, serialize=False)),
                ('vol_date_depart', models.DateTimeField()),
                ('vol_date_arrive', models.DateTimeField()),
                ('vol_lieu_depart', models.CharField(max_length=255)),
                ('vol_lieu_arrive', models.CharField(max_length=255)),
                ('vol_place_totale', models.IntegerField()),
                ('vol_place_restante', models.IntegerField()),
                ('vol_avion', models.CharField(max_length=255)),
                ('vol_prix', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('reservation_id', models.AutoField(primary_key=True, serialize=False)),
                ('reservation_nombre_personne', models.IntegerField()),
                ('reservation_nom', models.CharField(max_length=255)),
                ('reservation_date_creation', models.DateTimeField()),
                ('reservation_confirmation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='compagnie.achat')),
                ('reservation_vol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compagnie.vol')),
            ],
        ),
    ]
